services:
  # PostgreSQL Service
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prn222GradingSystem
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
    - grading-system-network
    
  # RabbitMQ Service      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Prn222GradingSystem
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - grading-system-network
  
  # MinIO Service
  minio:
    image: minio/minio
    container_name: minio
    ports:
        - "9000:9000"  # Port API 
        - "9001:9001"  # Port Console
    environment:
        - MINIO_ROOT_USER=admin
        - MINIO_ROOT_PASSWORD=Prn222GradingSystem
    command: server /data --console-address ":9001"
    volumes:
        - minio-data:/data
    networks:
        - grading-system-network
    
  # Qdrant Service
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  
      - "6334:6334"
    networks:
      - grading-system-network
    volumes:
      - qdrant-data:/qdrant/storage

  # Ollama Service
  ollama:
    build:
      context: .
      dockerfile: ./Docker/Ollama/Dockerfile
    hostname: ollama-service
    ports:
      - "11434:11434"
    networks:
      - grading-system-network

networks:
  grading-system-network:
    driver: bridge

volumes:
  rabbitmq-data:
  minio-data:
  qdrant-data:
  pg-data:  